### ISSUE TITLE
file upload drop area height not auto-resize

### ISSUE THREAD

**Issue by gifff** [bccfilkom/bcc-drophere-client#1]
![screenshot from 2017-09-09 09-36-28](https://user-images.githubusercontent.com/4391866/30236380-6ac08afc-9542-11e7-8142-290444db855f.png)

the file drop area is so small 👎

**Comment by renopp** [comment]
thanks for report it, we will fix it ASAP 🤣

**Comment by gifff** [comment]
now it's fixed. thanks a lot 😄
